### ISSUE TITLE
Establish user account types 

### ISSUE THREAD

**Issue by davoodharun** [AppliedIS/azure-blueprint#17]
- Individual User
- System / service user

**Comment by jomolesk** [comment]
Related control(s): AC-2.a

AC-2.a: The organization identifies and selects the following types of information system accounts to support organizational missions/business functions: [Assignment: organization-defined information system account types];

Information system account types include, for example, individual, shared, group, system, guest/anonymous, emergency, developer/manufacturer/vendor, temporary, and service.

**Comment by manishkumar-agarwal** [comment]
Hi @jomolesk 

This request focusses on creating users. I am thinking we would need to create below in AAD to demonstrate the same
1) Individual users
2) Groups
3) Guest Users
4) Individual users created would have different accesses based on RBAC

any other thing which would be needed for this one. Thanks

**Comment by jomolesk** [comment]
Hi @manishkumar-agarwal -- Yes, AAD individual users (e.g., security admin, web admin, DB admin). We do not need to have any guest users (number 3 in your comment).

**Comment by manishkumar-agarwal** [comment]
Hi @davoodharun @jomolesk  -- As discussed in our call today, the RBAC existing roles better support the PaaS services provided by Microsoft Azure.

Since we are using the IaaS VM's for hosting both the Web applications and SQL Servers, we will need to create groups and provide access at a resource(VM) level.

a) All the Web App Vm's will be given access to Web group
b) All the SQL Server Vm's will be given access to SQL group

The script for the creation of Custom-Role and providing access to the groups is ready, but all this will need Administrator access in AAD and the Azure RM cmdlets currently do not support creation of groups directly.

The Administrator will need to create groups for us 

Thanks
