### ISSUE TITLE
Anti-malware [SI-3(1), SI-3(2), SI-3(7)]

### ISSUE THREAD

**Issue by davoodharun** [AppliedIS/azure-blueprint#24]
- [x] Installed/configured on operating systems
  - [x] automatic signature updates
  - [x] periodic scanning
  - [x] real-time detection
  - [x] detection action(s)
  - [x] nonsignature-based detection
  - [x] logging/alerting
  - [x] OMS reporting
- [x] Application firewall
  - [x] Inbound/outbound traffic monitoring

**Comment by davoodharun** [comment]
a. Employs malicious code protection mechanisms at information system entry and exit points to detect and eradicate malicious code;

b. Updates malicious code protection mechanisms whenever new releases are available in accordance with organizational configuration management policy and procedures;

c. Configures malicious code protection mechanisms to:

1. Perform periodic scans of the information system [Assignment: **at least weekly**] and real-time scans of files from external sources at [Selection (one or more); endpoint; network entry/exit points] as the files are downloaded, opened, or executed in accordance with organizational security policy; and

2. [Selection (one or more): block malicious code; quarantine malicious code; send alert to administrator; [Assignment: organization-defined action]] in response to malicious code detection; and

d. Addresses the receipt of false positives during malicious code detection and eradication and the resulting potential impact on the availability of the information system.

**Comment by jomolesk** [comment]
Related controls: SI-3.a, SI-3.b, SI-3.c, SI-3 (1), SI-3 (2), SI-3 (7)

SI-3.a: The organization employs malicious code protection mechanisms at information system entry and exit points to detect and eradicate malicious code. [_This Azure Blueprint Solution deploys host-based antimalware protections for all deployed Windows virtual machines implemented using the Microsoft Antimalware virtual machine extension._]

SI-3.b: The organization updates malicious code protection mechanisms whenever new releases are available in accordance with organizational configuration management policy and procedures. [_This Azure Blueprint Solution deploys host-based antimalware protections for all deployed Windows virtual machines implemented using the Microsoft Antimalware virtual machine extension. This extension is configured to automatically update both the antimalware engine and protection signatures as release become available._]

SI-3.c: The organization configures malicious code protection mechanisms to 1) perform periodic scans of the information system [Assignment: **at least weekly**] and real-time scans of files from external sources at [Selection (one or more); **endpoints**; network entry/exit points] as the files are downloaded, opened, or executed in accordance with organizational security policy; and 2) [Selection (one or more): **block malicious code; quarantine malicious code; send alert to administrator in near real-time**; [Assignment: organization-defined action]] in response to malicious code detection. [_This Azure Blueprint Solution deploys host-based antimalware protections for all deployed Windows virtual machines implemented using the Microsoft Antimalware virtual machine extension. This extension is configured to perform both real-time and periodic scans (weekly), automatically update both the antimalware engine and protection signatures, perform automatic remediation actions, and provide notifications through **TBD: OMS/Azure Diagnostics**._]

SI-3 (1): The organization centrally manages malicious code protection mechanisms. **NOTE: OMS integration** [_This Azure Blueprint Solution deploys host-based antimalware protections for all deployed Windows virtual machines implemented using the Microsoft Antimalware virtual machine extension. Azure OMS provides a centralized capability to review the current status of the antimalware solution._]

SI-3 (2): The information system automatically updates malicious code protection mechanisms. [_This Azure Blueprint Solution deploys host-based antimalware protections for all deployed Windows virtual machines implemented using the Microsoft Antimalware virtual machine extension. This extension is configured to automatically update both the antimalware engine and protection signatures as release become available._]

SI-3 (7): The information system implements nonsignature-based malicious code detection mechanisms. [_This Azure Blueprint Solution deploys host-based antimalware protections for all deployed Windows virtual machines implemented using the Microsoft Antimalware virtual machine extension. This extension is configured to perform heuristic detection. **NOTE: need to confirm*_]

**Comment by JustinBacaAIS** [comment]
@davoodharun 
Not sure if this is a Windows Server 2016 issue, but when I deploy the extension in Azure Commercial to a 2016 VM using the portal I get a success and all is well.  There are no option in Azure Gov to add VM extension using portal.  The error I receive on the local VM when deploying IaaSAntimalware extension.
[05/15/2017 01:59:13.50] Executing: C:\Packages\Plugins\Microsoft.Azure.Security.IaaSAntimalware\1.3.0.0\AntimalwareConfig.exe -enable
[05/15/2017 01:59:14.38] Execution Complete.
######
Execution Output:
Microsoft Antimalware Configuration Utility
Version 6.0.6002.18518 (rd_security_n.150429-1431)
- Current UTC time: 5/15/2017 1:59:13 AM
- Utility has been started in JSON mode
- Microsoft Antimalware was pre-installed
- Configuration settings file found: C:\Packages\Plugins\Microsoft.Azure.Security.IaaSAntimalware\1.3.0.0\RuntimeSettings\0.settings
- Enabling antimalware
* ERROR: System.InvalidOperationException: Service MSMPSvc was not found on computer '.'. ---> System.ComponentModel.Win32Exception: The specified service does not exist as an installed service
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.GenerateNames()
   at System.ServiceProcess.ServiceController.get_ServiceName()
   at System.ServiceProcess.ServiceController.GenerateStatus()
   at System.ServiceProcess.ServiceController.get_Status()
   at Microsoft.Azure.Security.CampEngine.IsMsMpSvcRunning()
   at Microsoft.Azure.Security.CampEngine.Enable(AntimalwareConfig newConfig)
   at Microsoft.Azure.Security.Program.Main(String[] args)


Execution Error:

######
Command C:\Packages\Plugins\Microsoft.Azure.Security.IaaSAntimalware\1.3.0.0\AntimalwareConfig.exe of Microsoft.Azure.Security.IaaSAntimalware has exited with Exit code: 1

**Comment by JustinBacaAIS** [comment]
Get-AzureRmVMExtensionImage -Location usgovvirginia -PublisherName Microsoft.Azure.Security -Type IaaSAntimalware
Outputs only version: 1.3.0.0
This version does not work with Windows Server 2016

Azure Commercial (eastus) is currently supported up to version: 1.5.4.3
This version works with Windows Server 2016

**Comment by JustinBacaAIS** [comment]
@jomolesk @davoodharun 
The Dsc Resource WindowsDefender version 1.0.0.1 has issues in the Test-TargetResource function.  When executing the Compare-Objects cmdlet against Exclusions the reference and difference sets cannot be null otherwise the test fails and throws a terminating error.  I had to modify the Test-TargetResource function to validate if either set is null.  Newly provisioned VMs do not have Exclusions set by default which will always cause this Dsc Resource to fail.  I have updated the resource to version 1.0.0.2.  Ensure this is not overwritten by the Dsc Resource pulled from the Microsoft Gallery. 

Posted Comment [here](https://www.powershellgallery.com/packages/WindowsDefender/1.0.0.1)

**Comment by jomolesk** [comment]
@JustinBacaAIS
I was just looking through some things I have deployed in Azure Gov -- I have a Server 2012 R2 VM w/ the IaaSAntimalware extension enabled and working (and reporting to OMS). I also have a Server 2016 VM which is running Windows Defender (which, I believe it does out-of-the-box). Defender status is also reported to OMS. Although it's a two-solution implementation, it meets the control requirements so long as each solution is configured appropriately. The key think I want the solution to show (in OMS) is that all deployed VM hare malware protection installed. Here's the code from the 2012 R2 VM json:
```
        {
            "comments": "Generalized from resource: '/subscriptions/bfed0c87-ce95-4ac6-97f1-2ffecc584a05/resourceGroups/reston/providers/Microsoft.Compute/virtualMachines/blueprint-02/extensions/IaaSAntimalware'.",
            "type": "Microsoft.Compute/virtualMachines/extensions",
            "name": "[parameters('extensions_IaaSAntimalware_name_1')]",
            "apiVersion": "2016-04-30-preview",
            "location": "usgovvirginia",
            "properties": {
                "publisher": "Microsoft.Azure.Security",
                "type": "IaaSAntimalware",
                "typeHandlerVersion": "1.3",
                "autoUpgradeMinorVersion": true,
                "settings": {
                    "AntimalwareEnabled": true,
                    "RealtimeProtectionEnabled": "true",
                    "ScheduledScanSettings": {
                        "isEnabled": "true",
                        "day": "7",
                        "time": "120",
                        "scanType": "Full"
                    },
                    "Exclusions": {
                        "Extensions": "",
                        "Paths": "",
                        "Processes": ""
                    }
                }
            },
            "dependsOn": [
                "[resourceId('Microsoft.Compute/virtualMachines', parameters('virtualMachines_blueprint_02_name'))]"
            ]
        },
```

**Comment by JustinBacaAIS** [comment]
@jomolesk 
I'm looking at the error now and I was incorrect, I believe it's a parameter error on the exclusions.  For the WindowsDefender DSC Resource I have to pass an array for the IaaSAntimalware extension I have to pass a string with ; separated values.  Testing now.

**Comment by reetikatech** [comment]
Able to run and deploy in new resource group with provided steps it was successfully deployed yesterday. But for today displaying below error in template
for web application firewall enabled
ie. "wafEnabled": true
Deployment template validation failed: 'The value for the template parameter 'wafEnabled' at line '50' and column '20' is not provided. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'.

(Code: InvalidTemplate)
![image](https://cloud.githubusercontent.com/assets/26430269/26391233/687f8b84-407f-11e7-8832-dcc5448bb749.png)

**Comment by JustinBacaAIS** [comment]
# Anti-malware
Implemented using two (2) separate methods due to Azure Government's type handler version availability of the **IaaSAntimalware** extension.  Currently, Azure Government only has version 1.3.0.0 available, which supports operating systems earlier than Windows Server 2016.  In addition, the WindowsDefender DSC resource provided by Microsoft [here](https://www.powershellgallery.com/packages/WindowsDefender/1.0.0.1) is only compatible with Windows Server 2016 and has issues with null values when using exclusions and if there are no exclusions present on the system the WindowsDefender DSC resource is being deployed to and exclusions are being explicitly defined in the DSC extension, which is the case for this solution, an error will be thrown and the deployment will fail.  **This solution has a modified WindowsDefender DSC resource to fix the latter issue**.  Otherwise, remove exclusions from the template(s) and DSC script.

## Configuration
The WindowsDefender DSC Resource exclusion are implemented as an array of strings.  Each major VM role has its own path, extension, and process exclusions.  There is also a general exclusion parameter that is concatenated with each of these in order to apply a baseline as needed.  For the IaaSAntimalware extension all exclusions will need to be explicitly defined in each exclusion type's string.
### WindowsDefender DSC Resource
- **TARGETS**: Windows Server 2016 Datacenter (AD, Web, Mgt, & SQL Witness)
- **RealTimeScanDirection**: Both
- **RemediationScheduleDay** Everyday	
- **ScanScheduleDay**: Everyday
- **DisableRealtimeMonitoring**: false
- **Exclusions**:
  - **NOTE**: Exclusions are defined as an array of strings
  - **Paths**: 
    - **AD Recommended**: "f:\\ntds","f:\\sysvol","C:\\Windows\\SoftwareDistribution\\DataStore","C:\\Windows\\security\\database","C:\\Windows\\System32\\dns","C:\\Windows\\System32\\GroupPolicy"
    - **Web Recommended**: "C:\Windows\System32\inetsrv","C:\Windows\SysWOW64\inetsrv"
    - **Mgt Recommended**: 
    - **SQL Witness Recommended**: "f:\"
    - **Gen Recommended**: "c:\WindowsAzure"
  - **Extensions**: 
    - **AD Recommended**: ".dit"
    - **Web Recommended**: ".log"
    - **Mgt Recommended**: ".log"
    - **SQL Witness Recommended**: 
    - **Gen Recommended**: 
  - **Processes**:
    - **AD Recommended**: "dns.exe", "Microsoft.ActiveDirectory.WebServices.exe"
    - **Web Recommended**: "w3wp.exe"
    - **Mgt Recommended**: ".log"
    - **SQL Witness Recommended**: "sqlservr.exe","reportingservicesservice.exe","msmdsrv.exe"
    - **Gen Recommended**: "WaAppAgent.exe","WindowsAzureTelemetryService.exe","WindowsAzureGuestAgent.exe"
### IaaSAntimalware Extension
- **TARGETS**: Windows Server 2012 R2 (SQL Cluster VMs | sqlserver-0 & sqlserver-1) 
- **publisher**: Microsoft.Azure.Security,
- **typeHandlerVersion**: 1.3,
- **AntimalwareEnabled**: true,
- **Exclusions**:
  - **NOTE**: Exclusions are a single string separated by ";"
  - **Paths**: 
    - **Recommended**: "f:\logs;f:\data;C:\Program Files\Microsoft SQL Server;c:\WindowsAzure"
  - **Extensions**: 
    - **Recommended**: ".mdf;.ldf;.ndf;.bak;.trn;.trc;.sqlaudit;.sql"
    - **Default**: "w3wp.exe;explorer.exe"
    - **Recommended**: "sqlservr.exe;reportingservicesservice.exe;msmdsrv.exe;WaAppAgent.exe;WindowsAzureTelemetryService.exe;WindowsAzureGuestAgent.exe"
- **RealtimeProtectionEnabled**: true,
- **ScheduledScanSettings**:
  - **isEnabled**: true,
  - **scanType**: Full,
  - **day**: 0 (Everyday),
  - **time**: 60 (1:00 AM)
