### ISSUE TITLE
Communications protection

### ISSUE THREAD

**Issue by davoodharun** [AppliedIS/azure-blueprint#32]
- [ ] Web traffic secured
  - [ ] Application Gateway

**Comment by jomolesk** [comment]
Related control(s): AC-17 (2), SC-8, SC-8 (1), SC-23, SC-23 (1), SC-23 (3)

AC-17 (2): The information system implements cryptographic mechanisms to protect the confidentiality and integrity of remote access sessions. [_Auzre portal, remote desktop connection, and web application sessions are protected by cryptographic mechanisms._] (Also see issue #33.)

SC-8: The information system protects the [Selection: **confidentiality and integrity**] of transmitted information. [_SI-8 (1) implementation satisfies this control requirement._]

SC-8 (1): The information system implements cryptographic mechanisms to [Selection: **prevent unauthorized disclosure of information and detect changes to information**] during transmission unless otherwise protected by [Assignment: organization-defined alternative physical safeguards]. [_This Azure Blueprint Solution configures resources to communicate using only secure protocols. The WAF component of the Application Gateway is configured to accept communicators from external uses over HTTPS/TLS and communicate with the backend pool only over HTTPS/TLS. Similarly, the SQL Database is configured to communicate only over HTTPS/TLS._]

SC-23: The information system protects the authenticity of communications sessions. This control addresses communications protection at the session, versus packet level (e.g., sessions in service-oriented architectures providing web-based services) and establishes grounds for confidence at both ends of communications sessions in ongoing identities of other parties and in the validity of information transmitted. Authenticity protection includes, for example, protecting against man-in-the-middle attacks/session hijacking and the insertion of false information into sessions. [_**implementation TBD; web sessions, RDP, etc.**_]

SC-23 (1): The information system invalidates session identifiers upon user logout or other session termination. [_**implementation TBD; web sessions, RDP, etc.**_]

SC-23 (3): The information system generates a unique session identifier for each session with [Assignment: organization-defined randomness requirements] and recognizes only session identifiers that are system-generated. [_**implementation TBD; web sessions, RDP, etc.**_]
