### ISSUE TITLE
ExpressRoute (premium / v2 feature)

### ISSUE THREAD

**Issue by davoodharun** [AppliedIS/azure-blueprint#34]

**Comment by jomolesk** [comment]
Related control(s): AC-17 (3), SC-7 (3)

AC-17 (3): The information system routes all remote accesses through [Assignment: organization-defined number] managed network access control points.

SC-7 (3): The organization limits the number of external network connections to the information system. [_This Azure Blueprint solution deploys two public IP addresses: one associated with the Application Gateway; one associated with the management bastion host / jumpbox._] (Also see issue #31.)

**Comment by manishkumar-agarwal** [comment]
@jomolesk Hi

As part of the existing design, there are only two public IP addresses which are being specified. One linked to the Application Gateway and the other linked to Bastion host/jumpbox.

Based on my discussion with @davoodharun, there are testing scenarios where the testing would be done to check that the other VM's in the azure infrastructure cannot be accessed from outside of the Virtual Network.

Please let me know if the above specified is sufficient or we need to take up any additional action.

Thanks

**Comment by manishkumar-agarwal** [comment]
Hi @davoodharun 
As dicussed on this item, the current design is only supporting two public IP's in the infrastructure. Hence moving this issue over for testing

**Comment by reetikatech** [comment]
previously its displaying two public ip but today in Bprint700 ResourceGruop displaying three public ips. logged an issue.

![image](https://cloud.githubusercontent.com/assets/26430269/26246581/8f4b0d40-3cb7-11e7-9587-5e7114f2daa0.png)

**Comment by manishkumar-agarwal** [comment]
As part of the blueprint project design, there would be only two public IP addresses which are being specified. One linked to the Application Gateway and the other linked to Bastion host/jumpbox.

This issue is to ensure that there are only two public IP addresses deployed as part of the solution. All other infrastructure except  the  Application Gateway  and Bastion host/jumpbox should only be accessible from within the Virtual Network and for users with authorized access only.

For verification of this issue, please do the below.
1) Login to the Azure portal where the blueprint main template is deployed. There should be only 2 public IP addresses as part of the Resource group
2) Verify that the Application Gateway and Bastion host/jumpbox  are the ones which are linked to the public IP addresses.
3) Try to RDP into the  Application Gateway and Bastion host/jumpbox  from outside of Vnet. Connections should be established with valid credentials
4) Try to RDP to the other Web App VM's or SQL Server VMs using RDP from outside of Vnet. Connection should not be allowed
5) Try to RDP to Web App VM's or SQL Server VMs using RDP from inside of Vnet(Try RDP from inside of the Application gateway). Connections should be established with valid credentials

**Comment by reetikatech** [comment]
in reference to the above :verified and updated with comment
currently  there are two public ips :as expected.
![image](https://cloud.githubusercontent.com/assets/26430269/26493079/1e4ff1b8-4235-11e7-9847-2db8c03e1726.png)
